name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }

      - name: Install build deps
        run: |
          python -m pip install -U pip
          python -m pip install -U build pytest

      - name: Editable install
        run: python -m pip install -e .

      - name: Run tests
        run: python -m pytest
